
title: SYX的博客 # your title
url: 'https://github.com/prophet0122/prophet0122.github.io'
baseurl: 'prophet0122.github.io' #change it according to your repository name



# Profile information
yourname: Prophet  ## put your name
location: ChengDu , China


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
